repo_url: "https://fdroid.sidneyshelton.com/repo"
repo_name: "Northstar Works"
repo_description: |-
  Official F-Droid repository for Northstar Works apps.
  Add this repo in F-Droid: https://fdroid.sidneyshelton.com/repo

repo_icon: "icon.png"

archive_older: 3
