repo_url: "https://northstar-works.github.io/fdroid/repo"
repo_name: "Northstar Labs"
repo_description: |-
  Official F-Droid repository for Northstar Labs apps.
  Add this repo in F-Droid: https://northstar-works.github.io/fdroid/repo

#repo_icon: "icon.png"

archive_older: 3

repo_keyalias: sidscri-services


keydname: CN=sidscri-services, OU=F-Droid


keystorepass: ybfVldhs8X1VJS0YLQCpRhpR3Rjon9HgE/NOCej2vkc=


keypass: ybfVldhs8X1VJS0YLQCpRhpR3Rjon9HgE/NOCej2vkc=

